### PR TITLE
Add workflow steps for building

### PR DESCRIPTION
**Pull request by kevin-david**
And remove unnecessary action

### CODE REVIEW

**Comment by Yakov5776** [comment]
Why can't we add `npm i` as a workflow step so we don't need to track `node_modules` in git history?

**Comment by Yakov5776** [comment]
@kevin-david Also do you plan on bumping the release version? Since there are changes to the workflow inputs.

**Comment by kevin-david** [comment]
> Why can't we add `npm i` as a workflow step so we don't need to track `node_modules` in git history?

That's a good idea given the requirements for this repo, I'd rather not pollute diffs. Fixed in #16 

> @kevin-david Also do you plan on bumping the release version? Since there are changes to the workflow inputs.
 
Yeah I'll push out v2 shortly. I want to clean a few things up first

**Comment by kevin-david** [comment]
@Yakov5776 

> @kevin-david Also do you plan on bumping the release version? Since there are changes to the workflow inputs.

https://github.com/kevin-david/zipalign-sign-android-release/releases/tag/v2.0.0 is out - let me know if you see any issues.

**Comment by Yakov5776** [comment]
> @Yakov5776
> 
> > @kevin-david Also do you plan on bumping the release version? Since there are changes to the workflow inputs.
> 
> https://github.com/kevin-david/zipalign-sign-android-release/releases/tag/v2.0.0 is out - let me know if you see any issues.

Thank you, will take a look at it tomorrow or later tonight.

**Comment by Yakov5776** [comment]
> @Yakov5776
> 
> > @kevin-david Also do you plan on bumping the release version? Since there are changes to the workflow inputs.
> 
> https://github.com/kevin-david/zipalign-sign-android-release/releases/tag/v2.0.0 is out - let me know if you see any issues.

Either rename the tag to just `v2` or fix the readme to point to `v2.0.0` because it's supposed to be an exact tag.
Also you should probably do some testing because right off the bat it [fails for resolving a module](https://github.com/Yakov5776/testactions/actions/runs/10244077135/job/28336409719) - not sure why.

edit 1: I'd delete the tag for now, I was under the impression that `node_modules` wasn't needed since the `lib/main.js` includes it pre-bundled but that clearly isn't the case and it probably relied on it.

I wouldn't suggest adding it back as there's better solutions out there without tracking node_modules, for example if we add [ncc](https://github.com/vercel/ncc) as a second build step that could work.

edit 2: ncc seems to have built-in typescript support so we may even be able to ditch `tsc` altogether, if i get it working i'll send a patch.

edit 3: i have submitted a patch at https://github.com/kevin-david/zipalign-sign-android-release/pull/18, take a look.

**Comment by kevin-david** [comment]
> Also you should probably do some testing because right off the bat it [fails for resolving a module](https://github.com/Yakov5776/testactions/actions/runs/10244077135/job/28336409719) - not sure why.

I _think_ https://github.com/kevin-david/zipalign-sign-android-release/pull/20 will prevent this kind of mistake in the future!

**Pull request merged**
